version: '3.8'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    ports:
      - '1883:1883'
      - '9000:9000'
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwd.txt:/mosquitto/config/passwd.txt
      - ./mosquitto:/mosquitto/log
